#!/bin/bash

# Runs a single simulator test

members=${1:-1}
clients=${2:-1}
duration=${3:-1m}
testsuite=${4:-test}
outputDir=${5:-outputDir}

memberHeapSZ=4G
clientHeapSZ=2G

partitions=271
monitorSec=30

jfrArgs="-XX:+UnlockCommercialFeatures \
         -XX:+FlightRecorder \
         -XX:StartFlightRecording=duration=120m,filename=recording.jfr \
         -XX:+UnlockDiagnosticVMOptions \
         -XX:+DebugNonSafepoints"

gcArgs="-verbose:gc -Xloggc:verbosegc.log\
        -XX:+PrintGCTimeStamps \
        -XX:+PrintGCDetails \
        -XX:+PrintTenuringDistribution \
        -XX:+PrintGCApplicationStoppedTime \
        -XX:+PrintGCApplicationConcurrentTime \
        -XX:+HeapDumpOnOutOfMemoryError "

# both client and member get a fixated initial/max-heap size. This makes performance more stable

memberJvmArgs="-Dhazelcast.partition.count=${partitions} \
               -Dhazelcast.diagnostics.enabled=true -Dhazelcast.diagnostics.metric.level=info \
               -Xmx${memberHeapSZ} -Xms${memberHeapSZ}  \
               ${gcArgs} \
               ${jfrArgs} "

clientJvmArgs="-Xmx${clientHeapSZ} -Xms${clientHeapSZ} \
               ${gcArgs}
               ${jfrArgs} "

provisioner --kill

coordinator --duration ${duration} \
            --members ${members} \
            --workerVmOptions "${memberJvmArgs}" \
            --clients ${clients} \
            --clientWorkerVmOptions "${clientJvmArgs}" \
            --sessionId ${outputDir} \
            ${testsuite}.properties